---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wineinfo-catalog
  labels:
    app: wineinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wineinfo
      service: catalog
  template:
    metadata:
      labels:
        app: wineinfo
        service: catalog
    spec:
      containers:
      - name: main
        image: wineinfo-python:latest
        imagePullPolicy: IfNotPresent
        command: ["fastapi", "run", "/app/catalog_app.py", "--host", "0.0.0.0", "--port", "80"]
        envFrom:
        - configMapRef:
            name: wineinfo-config
        env:
        - name: CATALOG_DEMO_MOJIBAKE
          value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wineinfo-catalog-next
  labels:
    app: wineinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wineinfo
      service: catalog-next
  template:
    metadata:
      labels:
        app: wineinfo
        service: catalog-next
    spec:
      containers:
      - name: main
        image: wineinfo-python:latest
        imagePullPolicy: IfNotPresent
        command: ["fastapi", "run", "/app/catalog_app.py", "--host", "0.0.0.0", "--port", "80"]
        envFrom:
        - configMapRef:
            name: wineinfo-config
---
apiVersion: v1
kind: Service
metadata:
  name: wineinfo-catalog-next
spec:
  type: ClusterIP
  selector:
    app: wineinfo
    service: catalog-next
  ports:
    - port: 80
