---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wineinfo-embeddings
  labels:
    app: wineinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wineinfo
      service: embeddings
  template:
    metadata:
      labels:
        app: wineinfo
        service: embeddings
    spec:
      containers:
      - name: main
        image: wineinfo-python:latest
        imagePullPolicy: IfNotPresent
        command: ["fastapi", "run", "/app/embeddings_app.py", "--host", "0.0.0.0", "--port", "80"]
        envFrom:
        - configMapRef:
            name: wineinfo-config
        env:
        - name: RECS_DEMO_FAILURE
          value: "true"
