---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: wineinfo-catalog
  namespace: default
spec:
  replicas: 4
  strategy:
    canary:
      stableService: wineinfo-catalog
      canaryService: wineinfo-catalog-canary
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: wineinfo-catalog
            namespace: default
            useHeaderRoutes: true
        managedRoutes:
          - name: canary-route1
      steps:
        - setCanaryScale:
            replicas: 1
        - setHeaderRoute:
            name: canary-route1
            match:
              - headerName: baggage
                headerValue:
                  regex: .*username=admin(,|$).*
        - pause: {}
        - setCanaryScale:
            matchTrafficWeight: true
        - setHeaderRoute:
            name: canary-route1
        - setWeight: 25
        - pause: {}
        - setWeight: 100
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: wineinfo
      service: catalog
  template:
    metadata:
      labels:
        app: wineinfo
        service: catalog
    spec:
      containers:
        - name: main
          image: wineinfo-python:latest
          imagePullPolicy: IfNotPresent
          command:
            [
              "fastapi",
              "run",
              "/app/catalog_app.py",
              "--host",
              "0.0.0.0",
              "--port",
              "80",
            ]
          envFrom:
            - configMapRef:
                name: wineinfo-config
          env:
            - name: CATALOG_DEMO_MOJIBAKE
              value: "true"
